version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/bot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/scheduler"
    schedule:
      interval: "weekly"