version: "3"
services:
  postgres:
    image: "postgres:15"
    volumes:
      - "./.db-data/:/var/lib/postgresql/data"
      - "./bot/scripts/schemas/:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: "discord-gamestatus"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"
      PGDATA: "/var/lib/postgresql/data/12"
    env_file: .env
  bot:
#    image: "gamestatus/gamestatus-bot"
    build:
      context: "."
      dockerfile: "./docker/Dockerfile.bot"
    depends_on:
      - "postgres"
    volumes:
      - "./limit-rules.json:/home/node/limit-rules.json"
    environment:
      DISCORD_API_KEY: "${DISCORD_API_KEY}"
      TOPGG_API_KEY: "${TOPGG_API_KEY}"
      PG_DATABASE: "discord-gamestatus"
      PGHOST: "postgres"
      PGUSER: "discord-gamestatus"
      PGPASSWORD: "${DATABASE_PASS}"
      GS_PREFIX: "${GS_PREFIX}"
      GS_ADMIN_FLAG: "${GS_ADMIN_FLAG}"
      GS_TICK_COUNT: "${GS_TICK_COUNT}"
      GS_TICK_TIME: "${GS_TICK_TIME}"
      GS_CHANNEL_LIMIT: "${GS_CHANNEL_LIMIT}"
      GS_GUILD_LIMIT: "${GS_GUILD_LIMIT}"
      GS_SUPPORT_LINK: "${GS_SUPPORT_LINK}"
      GS_SCHEDULER_ADDR: "scheduler:1337"
    env_file: .env
    restart: on-failure
#    command: [ "--debug", "--verbose" ]
  scheduler:
#    image: "gamestatus/gamestatus-scheduler"
    build:
      context: "."
      dockerfile: "./docker/Dockerfile.scheduler"
    depends_on:
      - "postgres"
    environment:
      DISCORD_API_KEY: "${DISCORD_API_KEY}"
      PG_DATABASE: "discord-gamestatus"
      PGHOST: "postgres"
      PGUSER: "discord-gamestatus"
      PGPASSWORD: "${DATABASE_PASS}"
      GS_TICK_COUNT: "${GS_TICK_COUNT}"
      GS_TICK_TIME: "${GS_TICK_TIME}"
    env_file: .env
    restart: on-failure

