name: Bug Report
description: File a bug report
labels: ["bug","not-confirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-outcome
    attributes:
      label: What was the expected outcome?
      placeholder: Tell us what you expected to happen!
      value: "Nothing happened!"
    validations:
      required: true
  - type: dropdown
    id: self-host
    attributes:
      label: Self-host
      description: Are you self-hosted or using the public bot?
      options:
        - Public
        - Self-Hosted
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Bot version
      description: What version of the bot are you using, you can check this with `/botinfo`?
      value: 2.3.0
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Any extra information
  - type: textarea
    id: screenshot
    attributes:
      label: Attach a screenshot of your issue (if relevant).
