name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
      - '**.js'
      - '**.mjs'
      - '**.ts'
      - '**.sql'
      - '**.rs'
      - '.github/workflows/ci.yml' # This file
      - 'bot/requirements.txt'     # Sqlfluff version
      - 'bot/package.json'         # Test script or dependency versions
      - 'bot/tsconfig.json'        # TypeScript configuration
      - 'bot/.eslintrc.json'       # ESLint rules
      - 'bot/.sqlfluff'            # SQLFluff rules
      - 'clippy.toml'              # Clippy rules
  workflow_dispatch:               # Allow triggering manually

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./bot

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: bot/package-lock.json
    - name: Use python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
