name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
      - '**.js'
      - '**.ts'
      - '**.sql'
      - '**.rs'
      - '.github/workflows/ci.yml' # This file

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
      fail-fast: true
      max-parallel: 2

    steps:
    - uses: actions/checkout@v3
    - run: cd bot
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Use python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
