name: Node CI

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

  build:
    runs-on: ubuntu-latest
    needs: checkout

    strategy:
      matrix:
        node-version: [15.x, 16.x]
      fail-fast: true
      max-parallel: 2

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
