# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd bot
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
      # Workaround for git+ssh:// dependencies not working
      - run: |
          git config --global url."https://github.com/".insteadOf git@github.com
          git config --global url."https://".insteadOf ssh://
      - run: npm ci
      - run: npm run build --if-present


  publish-npm:
    needs: [build]
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd bot
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-docker:
    needs: [build]
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Build and push (bot)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.bot
          push: true
          tags: gamestatus/gamestatus-bot:latest
      - name: Build and push (scheduler)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.scheduler
          push: true
          tags: gamestatus/gamestatus-scheduler:latest

